### ISSUE TITLE
Add support for NIfTI-2

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/MIRTK#151]
Enable the ```NiftiImageReader``` to read [NIfTI-2](http://nifti.nimh.nih.gov/nifti-2) files. Possibly modify the ```NiftiImageWriter``` to use NIfTI-2 when the image is larger in one dimension than the maximum ```short``` value allows. The MIRTK has a limit imposed by the maximum ```int``` value, which can (must) be assumed to be less than the ```int64_t``` range supported by NIfTI-2.

When making this change, recognise when a file is CIFTI instead (cf. #150). The NiftiCLib possibly already cannot read CIFTI because these are not NIfTI-1 files.

**Comment by ghisvail** [comment]
Just adding this [reference](http://brainder.org/2015/04/03/the-nifti-2-file-format/), which details the difference between nii-1 and nii-2 and how to detect and convert from one format to the other.

**Comment by schuhschuh** [comment]
Reopening this issue because the ```NiftiImageReader``` does not actually use the I/O functions of the NIfTI C library and instead expects the magic number ```ni1``` or ```n+1``` in the first four bytes of the file. That is not the case for NIfTI-2 for which the magic numbers are further ```ni2``` and ```n+2```, respectively.
