### ISSUE TITLE
Rename "ImageIO" module to "IO"

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/MIRTK#159]
The currently named ```ImageIO``` module at the moment only provides image file readers and writers. However, given that the MIRTK can deal with images and point sets, it would be good to have a less specific name such as simply ```IO``` module which later on can also contain readers and writers for point sets. I am thinking in particular about the GIFTI format and the current wrappers of the VTK IO filters in the ```PointSet``` module. A separate ```PointSetIO``` module would be possible, but either there may be an overlap (VTK IO filters are there for both images and point sets) or the number of classes will always be rather limited.

**Comment by ghisvail** [comment]
:+1:
