### ISSUE TITLE
Support concatenation of a 2D slice to a 3D dataset

### ISSUE THREAD

**Issue by ghisvail** [BioMedIA/MIRTK#179]
As it stands currently, `mirtk concatenate-images` supports 2D-2D and 3D-3D concatenation to produce a 3D and 3D+T dataset respectively. Could the tool be improved to support 3D-2D concatenation, i.e. incremental stacking of 2D slices to a 3D datasets?

I am requesting this feature on behalf of Giacomo, who does not have time to report the issue himself.

**Comment by schuhschuh** [comment]
Sounds like a useful feature. PR from either party welcome.

**Comment by ghisvail** [comment]
I'll have a look at it.

**Comment by schuhschuh** [comment]
@ghisvail Do think this will be ready for the next release by the end of this week? Or shall I exclude it from this milestone?

**Comment by ghisvail** [comment]
It is a feature enhancement so I'd consider it not blocking. I don't think I'll find the time to complete it by the end of the week though. Let's move it to the next one.

**Comment by schuhschuh** [comment]
Been a while, but because @gtarroni brought up another issue with the tool, I've extended it now so you can provide both one volume and additional slices to create a new volume.
