### ISSUE TITLE
"Unknown CMake command continue" error on Ubuntu 14.04

### ISSUE THREAD

**Issue by ghisvail** [BioMedIA/MIRTK#197]
It seems that usage of `continue` is not compatible with cmake `2.8.12` on Ubuntu 14.04:
```
CMake Error at CMake/Basis/CommonTools.cmake:2760 (continue):
  Unknown CMake command "continue".
Call Stack (most recent call first):
  CMake/Basis/TargetTools.cmake:546 (basis_get_source_language)
  CMake/Basis/TargetTools.cmake:1036 (_basis_target_source_language)
  CMake/Modules/mirtkAddLibrary.cmake:52 (basis_add_library)
  Modules/IO/src/CMakeLists.txt:143 (mirtk_add_library)
```
Works fine on my Debian machine otherwise. Looks like this command was introduced in 3.0+? Can't see it listed for [2.8.12](https://cmake.org/cmake/help/v2.8.12/cmake.html), although `break` is.

**Comment by schuhschuh** [comment]
Interesting, thanks for reporting. Haven't tried with CMake 2.8.12 for some time. Am getting the same error and yes, the `continue` command wasn't available yet.
