### ISSUE TITLE
Fix byte swapping

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/MIRTK#217]
Currently, byte swapping is always enabled when writing and reading a file with the ```Cofstream``` and ```Cifstream```. This should be changed to use a consistent byte order, i.e., either little or big endian for all binary files. Swapping should only take place if necessary. For transformation files, the magic number can be used to determine whether byte swapping is needed or not. This would then also ensure that older files written in a possibly inconsistent byte order are still be able to be read.

**Comment by schuhschuh** [comment]
The endianess is mainly used by the ```Cifstream``` and ```Cofstream``` classes of the Common module which intend to store the binary data always in big endian order. The same is true for the ```std::ostream``` and ```std::istream``` operators of the ```Matrix``` and ```Vector``` classes of the Numerics module. The IRTK implementation used a compile time definition ```WORDS_BIGENDIAN``` to decide whether the data needs to be swapped (compile definition missing) or not. Assuming that it is run on a modern Linux system which seems to be little endian (at least my machine with Ubuntu 14.04), this compile definition was never set in the CMakeLists.txt of IRTK. The same is currently the case for MIRTK to maintain "backwards compatibility". In this case, however, we will have to break it for users that were running the commands on a big endian system. For those, the binary files have little endian order instead of big endian. However, to not be depending on the endianess when transferring/exchanging files between users, we'll have to choose a common endianess. This should only affect matrices and vectors stored as binary files. In case of transformation files we are able to detect the endianness of the binary data stored in the file.

**Comment by ghisvail** [comment]
> In this case, however, we will have to break it for users that were running the commands on a big endian system. For those, the binary files have little endian order instead of big endian.

Ack. Nothing we can do about it besides keeping the same default as in IRTK as you said earlier. 

> modern Linux system which seems to be little endian.

Actually, it is architecture dependent. Architectures like `arm`, `powerpc` and `mips` all have big endian variants, can run a modern Linux distribution and are used to build cheap processing racks.

> The same is currently the case for MIRTK to maintain "backwards compatibility".

Sounds sensible.

> However, to not be depending on the endianess when transferring/exchanging files between users, we'll have to choose a common endianess.

Or modify our binary format to allow detection of endianness, which is the usual purpose of the so called "magic numbers". Or use an existing format which is already endianness agnostic, perhaps the `mat` format via `libmatio`?

**Comment by schuhschuh** [comment]
I'll opt to change the current code to always write binary data in big endian byte order, with a simple runtime check whether the system is little or big endian, i.e., whether the bytes in the memory need to be swapped after/before to the I/O operation.

The ```mat``` format is currently supported as an alternative when the library is build ```WITH_MATLAB```. Using the ```libmatio``` instead of linking to the MATLAB Compiler Runtime libraries would be good for this. But that is another issue.

**Comment by ghisvail** [comment]
Alright then, big endian it is.
