### ISSUE TITLE
Create Snappy package / AppImage

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/MIRTK#221]
Just out of curiousity, this may be a neat way to distribute MIRTK for Ubuntu users without the restriction of dependency versions available as deb packages for the respective Ubuntu release. For Ubuntu 14/16, this isn't really a problem with the current MIRTK source code, though, as these come with recent enough packages via apt-get. Would still be interesting to look into this new Snapcrafting...

https://developer.ubuntu.com/en/desktop/
https://developer.ubuntu.com/en/snappy/build-apps/

**Comment by probonopd** [comment]
...or [AppImageKit](https://github.com/probonopd/AppImageKit). Linus [describes](https://plus.google.com/+LinusTorvalds/posts/WyrATKUnmrS) it like this: 

> It not only allows for a project to create a complex Linux application (...) that works on multiple distributions, you don't even need to really even install it. Download a file, mark it executable, and run it.
> It comes with its own little embedded compressed ISO filesystem that gets mounted and contains all the required libraries.

**Comment by schuhschuh** [comment]
@probonopd AppImageKit seems cool and would be available for a broader user base. Both, Snappy packages and AppImages remind me of OS X bundles... glad this is coming to Linux now.

**Comment by schuhschuh** [comment]
Seems Snap packages can be installed and run on various distributions now/soon as well... http://arstechnica.com/information-technology/2016/06/goodbye-apt-and-yum-ubuntus-snap-apps-are-coming-to-distros-everywhere/

**Comment by ghisvail** [comment]
It is very early days to tell TBH. We have several of this so-called "universal" packages (AppImage, Flatpak, Snap) competing for a share of the Linux cake, but these projects are still a bit young to make an informed choice I believe. Nonetheless, these technologies *should* be able to coexist.

Regarding the article you linked, Ars is basically rephrasing Canonical PR and adds a somewhat click-baity title to it. I prefer this comparatively less biased and more factual article from the [register](http://www.theregister.co.uk/2016/06/14/universal_ubuntu_snap_packages/).

**Comment by schuhschuh** [comment]
Sure, but IMHO, given the fact that Snappy is supported natively by Ubuntu and marketed by them, and given that the de-facto standard home user (and research user, our main stackholder) Linux distro of choice being Ubuntu, I would rather bet on Snappy rather than any of these other much less known solutions to come out on top.

**Comment by schuhschuh** [comment]
@probonopd Thanks for the tip! AppImage has convinced me and using the created file the same as we would use the `mirtk` Python wrapper script (by dropping the `.AppImage`) extension, is pretty cool. See #610 description.
