### ISSUE TITLE
Make "develop" the "master" branch

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/MIRTK#232]
The release branch is still handy to have a Docker image only created automatically when pushing to the release branch. The master branch will be used for PR merges and continued development. For each release, the final release is merged into and pushed to the release branch.

**Comment by ghisvail** [comment]
> The release branch is still handy to have a Docker image only created automatically when pushing to the release branch.

Can't this be sync'd when pushing a release **tag** instead?

**Comment by schuhschuh** [comment]
> Can't this be sync'd when pushing a release tag instead?

I've checked the settings on Docker Hub, and yes, it can be triggered by a tag instead.

**Comment by ghisvail** [comment]
> Make "develop" the "master" branch
 
:+1:
