### ISSUE TITLE
CI for Windows build using AppVeyor

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/MIRTK#249]
https://www.appveyor.com/

**Comment by ghisvail** [comment]
Yep, that would be awesome. That way we can tick the "works on Windows" label.

**Comment by schuhschuh** [comment]
And that requires some PowerShell scripting to get the dependencies installed. Unfortunately many of these are not available via [Chocolatey](https://chocolatey.org), which seems to be cool thing just like [NuGet](https://www.nuget.org/) for Windows developers. A reference may be the [.appveyor.yml of gadomski/fgt](https://github.com/gadomski/fgt/blob/f2fe5fd9dbbff6184af595594d77ab07301cd1ff/.appveyor.yml). That's the project that made me aware of the existence of AppVeyor. Hopefully we can also use the [binary release packages of VTK](http://www.vtk.org/download/). Need to see if these "Standalone Python Interface (Installer)" packages are suitable, though.

Otherwise it should be feasible to pre-package the pre-requisites for VS 2015 into a single zip archive and upload it to [BinTray](https://bintray.com/) or something else. I've got all the libraries build on Windows 7.

**Comment by ghisvail** [comment]
Seems that you know what you are doing. I have only watched AppVeyor from the sideline so I cannot be of more help beyond moral support at this point.

> schuhschuh added this to the v1.2.0 milestone

:+1: although let's not make it a blocker.
