### ISSUE TITLE
Non-deterministic results of multi-threaded registration with NMI

### ISSUE THREAD

**Issue by stefanpsz** [BioMedIA/MIRTK#300]
I've run the same rigid+affine registration both in Windows and Linux and I get non deterministic result when running multithreaded with NMI **or across platforms**

To summarise:

4 multi threaded runs on Windows: Identical runs 1, 3 and 4. run 2 yielded different results.
6 single threaded runs on Windows: 6 identical runs, which in turn are identical to runs 1,3 and 4 above.

4 multi threaded runs on Linux: All 4 yielded different results.
3 single threaded runs on Linux: 3 identical runs, which are all different to any of the 4 multi threaded runs on Linux **and also different to the single threaded runs on Windows.**

All runs with SSD as similarity are identical, regardless of number of threads or platform. 

Attached parameter files:
[params.zip](https://github.com/BioMedIA/MIRTK/files/293891/params.zip)

**Comment by schuhschuh** [comment]
Perfect, thanks for testing it out and the summary. The issue with the NMI / joint histogram filling seems to crumble up again. There are some notes in the code where I disabled the multi-threaded execution for parts that at the time I believed were causing such differences. Seems I was not catching all or the right parts of code then.

One question, when you say Window and Linux, are these different physical machines? Or are both systems running on the same machine. If so, in a virtual environment, or multi-boot?

**Comment by stefanpsz** [comment]
@schuhschuh They are indeed completely different physical machines.

**Comment by stefanpsz** [comment]
To add to the discussion.

Attached are the results for one run on Windows and two runs on Linux. In the Linux case I had to run the registration several times before getting a different result. From what I can recall I would say this "different" result is not completely random, but something I might have gotten yesterday. This means that apparently there are not "infinite" different results you can get, but only two (or maybe three).

From the results, I would say the first run on Linux is the correct one (or at least the one that looks better)

[results.zip](https://github.com/BioMedIA/MIRTK/files/295177/results.zip)

**Comment by schuhschuh** [comment]
@amakropoulus reported the same issue with FFD registration using NMI. That's where the problem is most likely, the similarity measure.

**Comment by schuhschuh** [comment]
This issue seems to be caused by an uninitialized boolean flag `_UseParzenWindow` that I've added [with this commit](https://github.com/BioMedIA/MIRTK/commit/8129d2ec9d4d50b86723bda627f6f3081f11e861#diff-917ab94b3121042e96e929c7aeab03beR77) 12 April. Some time it would run the `Histogram2D::Smooth` function, and other times it wouldn't.

**Comment by schuhschuh** [comment]
This issue demands a bug-fix release as it affects release version 1.1!

**Comment by schuhschuh** [comment]
I now obtain the same results for `-model Rigid+Affine -sim NMI` on both my Ubuntu 14.04 with GCC 4.8.4 and OS X 10.11 with clang 7.3.0.

**Comment by schuhschuh** [comment]
Confirmed again that results on the same machine are always the same using `Rigid+Affine+FFD`. Results between machines may differ... another issue.
