### ISSUE TITLE
How to discover VTK version >= 6 without VTKConfigVersion.cmake issues

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/MIRTK#45]
The ```VTKConfigVersion.cmake``` file requires since version 6 that the major version number matches exactly the requested (minimum) version. This is very uncommon behavior and changes the meaning of the VERSION argument of ```find_package```. So far, it was a "minimum required" version. Now it is more like a "exact major version" match. IMHO, that's a mistake on VTK's end. When somebody has VTK 7 already, they are now seeing still an error when setting ```DEPENDS_VTK_DIR``` that version 6 is required. Version 7 is not accepted by CMake because it is marked as not compatible with version 6 by ```VTKConfigVersion.cmake```. One solution is to not request any particular VTK version in the CMake files of MIRTK, but only mention the minimum required version in the documentation.

**Comment by ghisvail** [comment]
So what you are saying is that `find_package(VTK 6.1)` would accept VTK version 6.X with X >= 1 but not 7.0, am I correct ?

**Comment by schuhschuh** [comment]
Yes.

**Comment by ghisvail** [comment]
That's not too surprising since it is a major version bump. That way you force downstream to make sure they are compatible, instead of blindly accepting any later version (major or not). Being in charge of packaging VTK 7 for Debian, trust me VTK major transitions have proven not to be always a walk in the park.

**Comment by schuhschuh** [comment]
Well, but it's still inconvenient because Cake provides you with no mechanism to say that your software is compatible with more than one major version.

**Comment by ghisvail** [comment]
I agree it is not ideal, but I understand the rationales behind their design. I guess we'll have to bite the bullet and either implement the so-called "hack" of version testing or do subsequent `find_package` calls for 6 and then 7.

**Comment by ghisvail** [comment]
AFAIK, we are minimum `6.1` because of C++11 right? Or do we need a later version now?

**Comment by schuhschuh** [comment]
I don't think it's because of C++11. Most code builds fine with VTK 5.10, but I haven't payed attention to this any longer. Any VTK 6+ version should be fine.

**Comment by ghisvail** [comment]
It should be. See http://www.paraview.org/Bug/view.php?id=14164

**Comment by ghisvail** [comment]
They say fixed in `6.0.1` which was never released officially AFAIK, so `6.1`?

**Comment by schuhschuh** [comment]
I see, good this bug report is referenced here now. So yeah, 6.1 it is.

**Comment by schuhschuh** [comment]
Minimum VTK version is now 6.0.0. See PR #107.
