### ISSUE TITLE
Add split-volume/split-sequence commands

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/MIRTK#621]
A `extract-image-regions` command similar to IRTK's `split-volume` would be nice instead of having to call `extract-image-region` individually for each slice in a volume/sequence or each volume in a sequence, respectively.

Alternatively, can `extract-image-region` be extended to cover extraction of multiple image regions at once?

Possibly provide simpler wrapper scripts `split-volume` and `split-sequence` for the more common use cases.

**Comment by schuhschuh** [comment]
@gtarroni When PR #624 is merged, you can:

Save the slices of a cardiac image stack using:
```
mirtk extract-image-slice stack.nii.gz slice_%03d.nii.gz
```

Or only save a common ROI of each slice with:
```
mirtk extract-image-region stack.nii.gz roi_%03d.nii.gz -Rx1 50 -Rx2 150 -Ry1 20 -Ry2 100 -split z
```

Create a stack from 2D slices using the previously fixed command:
```
mirtk combine-images slice_???.nii.gz stack.nii.gz
```

Append another slice to the stack using:
```
mirtk combine-images -input stack.nii.gz -image slice.nii.gz -nosort -output result.nii.gz
```

**Comment by gtarroni** [comment]
Awesome!! Thanks a lot
