### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [BioMedIA/MIRTK#645]
\Modules\Numerics\src\Matrix.cc line 1028

is.get() != ' '

**Comment by schuhschuh** [comment]
Thanks, I'm not sure there is really a mistake. Note that `is.get()` extracts a character from the input stream. So the second `is.get()` will not be identical to the previous `is.get()`. It's maybe a bit of an odd way to parse the input this way, but it is a nice "left-to-right" line of code to check if the input stream contains a specific string / pattern.

**Comment by maddin200** [comment]
of course  you are correct - here is true one:
\Applications\src\evaluate-overlap.cc line 162
else if (str == "fnr" || str == "falsenegativerate" || str == "falsenegativerate" ||
