### ISSUE TITLE
Eigen3 not found on Windows 7

### ISSUE THREAD

**Issue by satrajitgithub** [BioMedIA/MIRTK#665]
Hi. When I am trying to build MIRTK using CMake, it throws the following error

`CMake Error at CMake/Basis/CommonTools.cmake:840 (message):
  

  Module Numerics requires Eigen3.  Please ensure that the package is
  installed in a standard system location or set DEPENDS_Eigen3_DIR to the
  installation prefix (i.e., root directory of the installation).

  The DEPENDS_Eigen3_DIR variable can alternatively be set to the directory
  containing a Eigen3Config.cmake or eigen3-config.cmake file.  If no such
  file exists, contact either the developer of this project or CMake BASIS to
  provide a FindEigen3.cmake file.

Call Stack (most recent call first):
  CMake/Basis/ProjectTools.cmake:2134 (basis_find_package)
  CMake/Basis/ProjectTools.cmake:2428 (basis_find_packages)
  CMake/Modules/mirtkProjectBegin.cmake:90 (basis_project_begin)
  CMake/Modules/mirtkConfigureModule.cmake:41 (mirtk_project_begin)
  Modules/Numerics/CMakeLists.txt:28 (mirtk_configure_module)`

I tried setting the DEPENDS_Eigen3_DIR to the bin folder of Eigen where the Eigen3Config.cmake file exists but it still doesn't work.

**Comment by schuhschuh** [comment]
Hey, sorry for the late reply. The `DEPENDS_Eigen3_DIR` should be the top-level directory to which you extracted the Eigen3 source code zip file downloaded from http://eigen.tuxfamily.org/index.php?title=Main_Page. Closing this for now, but if this is still an issue and you would like it resolved, feel free to reopen. Thanks!
