### ISSUE TITLE
Missing delete[] in mirtkPolyDataSmoothing

### ISSUE THREAD

**Issue by maddin200** [BioMedIA/MIRTK#68]
Modules\PointSet\src\mirtkPolyDataSmoothing.cc line 668 missing: delete [] dir;

**Comment by schuhschuh** [comment]
Thanks, made the changes locally and will submit a PR soon.

**Comment by maddin200** [comment]
Am 11.02.2016 um 15:14 schrieb Andreas Schuh:
>
> Thanks, made the changes locally and will submit a PR soon.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/BioMedIA/MIRTK/issues/68#issuecomment-182881881>.
>
I think there is the same issue in line 885 (same file).

**Comment by schuhschuh** [comment]
Yes, I've already modified bot locations.
