### ISSUE TITLE
edit-image: modifies fourth voxel dimension in a 3D image in unexpected ways

### ISSUE THREAD

**Issue by soundray** [BioMedIA/MIRTK#695]
Changes dimension t from 1000 to 1 (expected 4):
```
$ info ref.nii.gz | grep dimensions
Image dimensions are 176 198 160 1
Voxel dimensions are 0.937 0.937 0.937 1000
$ edit-image ref.nii.gz edt.nii.gz -size 1 2 3 4
$ info edt.nii.gz | grep dimensions
Image dimensions are 176 198 160 1
Voxel dimensions are 1 2 3 1
$ info com.nii.gz | grep dimensions
Image dimensions are 176 198 160 1
Voxel dimensions are 0.937 0.937 0.937 1
```
It works as expected if there is more than one timepoint
```
$ info 4d.nii.gz | grep dimensions
Image dimensions are 176 198 160 7
Voxel dimensions are 0.937 0.937 0.937 0.001
$ edit-image 4d.nii.gz edt.nii.gz -size 1 2 3 4
$ info edt.nii.gz | grep dimensions
Image dimensions are 176 198 160 7
Voxel dimensions are 1 2 3 4
```

**Comment by schuhschuh** [comment]
Thanks, that's odd indeed. As a work-around, you could also use option `-dt` to change only the temporal voxel size. Does that work as expected?

**Comment by schuhschuh** [comment]
PS: Tried it, `-dt` behaves equally strange.

**Comment by schuhschuh** [comment]
This seems to be caused by the `NiftiImageWriter`. Because the verbose output shows that the tool correctly updated the image attributes before passing the image on to the writer:

```
$ mirtk edit-image seg95.nii.gz edt.nii.gz -size 1 2 3 4 -v                                                                                                    0 < 17:39:44
Image lattice:
  Size:            176 x        198 x        160
  Spacing:     1.00000 x    2.00000 x    3.00000 x    4.00000
  Origin:  [  -0.00000 ,   -0.00000 ,   -0.00001 ,    0.00000]
  X-axis:  [   1.00000 ,    0.00000 ,    0.00000]
  Y-axis:  [   0.00000 ,    1.00000 ,    0.00000]
  Z-axis:  [   0.00000 ,    0.00000 ,    1.00000]
Foreground mask:  No
Background value: n/a
```

**Comment by schuhschuh** [comment]
The setting of `ndim = 3` for the NIfTI image is the culprit. The NIfTI-2 library then simply discards the `pixdim` values for higher dimensions. When loading the data back, the spacing is simply set to the default value of 1 as it it is not read from the image file (because `ndim = 3`).

https://github.com/BioMedIA/MIRTK/blob/777c5be299cd24506130ec8279ce39756ac7bb77/Modules/IO/src/NiftiImage.cc#L81

I presume always setting `ndim = 4` (or 5 for vector-valued images) wouldn't hurt...

**Comment by soundray** [comment]
Tested -- problem fixed. Thanks @schuhschuh
