### ISSUE TITLE
gcc 8 memory leak issue in Surface Collision routine

### ISSUE THREAD

**Issue by chrisadamsonmcri** [BioMedIA/MIRTK#708]
Fantastic work on MIRTK Andreas.

I have been using ubuntu 18.04 to compile and run MIRTK. I have tried to compile with gcc/g++ 8 and gcc/g++ 9 under 19.10. I'm getting segmentation faults in MIRTK/MIRTK/Modules/PointSet/src/SurfaceCollisions.cc
void operator ()(const blocked_range<vtkIdType> &re) const

The addresses for ptIds and pts1 and pts2 get overwritten. I suspect a memory leak somewhere but I'm lost at the moment.

**Comment by chrisadamsonmcri** [comment]
It is the vtkIntersectionPolyDataFilter with tolerance=0 writes to invalid memory causing segfault issue you raised.

https://gitlab.kitware.com/vtk/vtk/issues/17012

I fixed it in vtkIntersectionPolyDataFilter.cxx by ramping the tolerance by 10 until it sets ts1 and ts2 properly.

**Comment by chrisadamsonmcri** [comment]
Here is the patch that I applied to VTK 8.2.0
[intersection_test.txt](https://github.com/BioMedIA/MIRTK/files/3819305/intersection_test.txt)

**Comment by schuhschuh** [comment]
Hi Chris, thanks for sharing and finding this bug in VTK!

**Comment by schuhschuh** [comment]
I'm curious, as the VTK issue suggests a fix has been released with VTK 8.1.1, but you say you encountered this issue with VTK 8.2?

Was the fix by the VTK developers not effective for your case?

Link to their fix: https://gitlab.kitware.com/vtk/vtk/merge_requests/4264

**Comment by chrisadamsonmcri** [comment]
Actually I spoke too soon.

This triangle pair intersects but the t values that I get are not close to 1. The ts1 index is never set and causes a segmentation fault.

V = [0.857644 27.2629 1.31268; ...
1.22082 27.2912 0.748195; ...
0.665803 26.955 0.30146; ...
1.76801 37.0102 -20.7337; ...
2.18434 -25.1474 -28.5257; ...
-0.236432 31.3283 24.4838];

F = [1 2 3; 4 5 6];
