### ISSUE TITLE
static build failed

### ISSUE THREAD

**Issue by Mon-ius** [BioMedIA/MIRTK#762]
/rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -S/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK -B/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build --check-build-system CMakeFiles/Makefile.cmake 0
/rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -E cmake_progress_start /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/CMakeFiles /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make -f ThirdParty/LBFGS/CMakeFiles/LibLBFGS.dir/build.make ThirdParty/LBFGS/CMakeFiles/LibLBFGS.dir/depend
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
cd /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build && /rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -E cmake_depends "Unix Makefiles" /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/ThirdParty/LBFGS /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/ThirdParty/LBFGS /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/ThirdParty/LBFGS/CMakeFiles/LibLBFGS.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make -f ThirdParty/LBFGS/CMakeFiles/LibLBFGS.dir/build.make ThirdParty/LBFGS/CMakeFiles/LibLBFGS.dir/build
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make[2]: Nothing to be done for 'ThirdParty/LBFGS/CMakeFiles/LibLBFGS.dir/build'.
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
[  0%] Built target LibLBFGS
make -f Modules/Common/src/CMakeFiles/LibCommon.dir/build.make Modules/Common/src/CMakeFiles/LibCommon.dir/depend
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
cd /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build && /rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -E cmake_depends "Unix Makefiles" /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/Common/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/Common/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/Common/src/CMakeFiles/LibCommon.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make -f Modules/Common/src/CMakeFiles/LibCommon.dir/build.make Modules/Common/src/CMakeFiles/LibCommon.dir/build
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make[2]: Nothing to be done for 'Modules/Common/src/CMakeFiles/LibCommon.dir/build'.
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
[  5%] Built target LibCommon
make -f Modules/Numerics/src/CMakeFiles/LibNumerics.dir/build.make Modules/Numerics/src/CMakeFiles/LibNumerics.dir/depend
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
cd /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build && /rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -E cmake_depends "Unix Makefiles" /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/Numerics/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/Numerics/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/Numerics/src/CMakeFiles/LibNumerics.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make -f Modules/Numerics/src/CMakeFiles/LibNumerics.dir/build.make Modules/Numerics/src/CMakeFiles/LibNumerics.dir/build
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make[2]: Nothing to be done for 'Modules/Numerics/src/CMakeFiles/LibNumerics.dir/build'.
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
[ 15%] Built target LibNumerics
make -f Modules/Image/src/CMakeFiles/LibImage.dir/build.make Modules/Image/src/CMakeFiles/LibImage.dir/depend
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
cd /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build && /rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -E cmake_depends "Unix Makefiles" /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/Image/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/Image/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/Image/src/CMakeFiles/LibImage.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make -f Modules/Image/src/CMakeFiles/LibImage.dir/build.make Modules/Image/src/CMakeFiles/LibImage.dir/build
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make[2]: Nothing to be done for 'Modules/Image/src/CMakeFiles/LibImage.dir/build'.
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
[ 31%] Built target LibImage
make -f Modules/IO/src/CMakeFiles/nifticlib.dir/build.make Modules/IO/src/CMakeFiles/nifticlib.dir/depend
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
cd /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build && /rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -E cmake_depends "Unix Makefiles" /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/IO/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/IO/src/CMakeFiles/nifticlib.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make -f Modules/IO/src/CMakeFiles/nifticlib.dir/build.make Modules/IO/src/CMakeFiles/nifticlib.dir/build
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make[2]: Nothing to be done for 'Modules/IO/src/CMakeFiles/nifticlib.dir/build'.
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
[ 31%] Built target nifticlib
make -f Modules/IO/src/CMakeFiles/gifticlib.dir/build.make Modules/IO/src/CMakeFiles/gifticlib.dir/depend
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
cd /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build && /rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -E cmake_depends "Unix Makefiles" /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/IO/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/IO/src/CMakeFiles/gifticlib.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make -f Modules/IO/src/CMakeFiles/gifticlib.dir/build.make Modules/IO/src/CMakeFiles/gifticlib.dir/build
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make[2]: Nothing to be done for 'Modules/IO/src/CMakeFiles/gifticlib.dir/build'.
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
[ 32%] Built target gifticlib
make -f Modules/IO/src/CMakeFiles/metaio.dir/build.make Modules/IO/src/CMakeFiles/metaio.dir/depend
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
cd /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build && /rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -E cmake_depends "Unix Makefiles" /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/IO/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/IO/src/CMakeFiles/metaio.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make -f Modules/IO/src/CMakeFiles/metaio.dir/build.make Modules/IO/src/CMakeFiles/metaio.dir/build
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make[2]: Nothing to be done for 'Modules/IO/src/CMakeFiles/metaio.dir/build'.
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
[ 33%] Built target metaio
make -f Modules/IO/src/CMakeFiles/LibIO.dir/build.make Modules/IO/src/CMakeFiles/LibIO.dir/depend
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
cd /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build && /rds/bear-apps/2020a/EL8-p9/software/CMake/3.16.4-GCCcore-9.3.0/bin/cmake -E cmake_depends "Unix Makefiles" /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/IO/src /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/IO/src/CMakeFiles/LibIO.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make -f Modules/IO/src/CMakeFiles/LibIO.dir/build.make Modules/IO/src/CMakeFiles/LibIO.dir/build
make[2]: Entering directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
[ 33%] Building CXX object Modules/IO/src/CMakeFiles/LibIO.dir/IOConfig.cc.o
cd /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/Modules/IO/src && /rds/bear-apps/2020a/EL8-p9/software/GCCcore/9.3.0/bin/c++  -DHAVE_EXPAT -DHAVE_MIRTK_Common -DHAVE_MIRTK_Image -DHAVE_MIRTK_Numerics -DHAVE_PNG -DHAVE_VTK -DHAVE_ZLIB -DMIRTK_IO_STATIC_DEFINE -DMIRTK_WITH_PROFILING -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/src -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/include -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build/include -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/src -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/include -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/Common/include -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/Numerics/include -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/Image/include -I/rds/bear-apps/2020a/EL8-p9/software/libpng/1.6.37-GCCcore-9.3.0/include -I/rds/bear-apps/2020a/EL8-p9/software/zlib/1.2.11-GCCcore-9.3.0/include -I/rds/bear-apps/2020a/EL8-p9/software/expat/2.2.9-GCCcore-9.3.0/include -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/src/meta -I/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/ThirdParty/LBFGS/include -isystem /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/library/include/vtk-9.0  -O3 -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/LibIO.dir/IOConfig.cc.o -c /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/src/IOConfig.cc
In file included from /rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/src/IOConfig.cc:35:
/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/include/mirtk/MetaImageReader.h:46:13: error: ‘MetaImage’ was not declared in this scope; did you mean ‘MetaIamge’?
   46 |   UniquePtr<MetaImage> _MetaImage;
      |             ^~~~~~~~~
      |             MetaIamge
/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/include/mirtk/MetaImageReader.h:46:22: error: template argument 1 is invalid
   46 |   UniquePtr<MetaImage> _MetaImage;
      |                      ^
/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/Modules/IO/include/mirtk/MetaImageReader.h:73:25: error: ‘MetaImage’ does not name a type; did you mean ‘MetaIamge’?
   73 |   void CopyHeader(const MetaImage &);
      |                         ^~~~~~~~~
      |                         MetaIamge
make[2]: *** [Modules/IO/src/CMakeFiles/LibIO.dir/build.make:63: Modules/IO/src/CMakeFiles/LibIO.dir/IOConfig.cc.o] Error 1
make[2]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'
make[1]: *** [CMakeFiles/Makefile2:1523: Modules/IO/src/CMakeFiles/LibIO.dir/all] Error 2
make[1]: Leaving directory '/rds/projects/d/duanj-ai-in-medical-imaging/castles/.share/2020a-gcc9.3/download/MIRTK/build'

**Comment by schuhschuh** [comment]
There's been a typo in `MetaImageReader.h`. Changed `class MetaIamge;` to `class MetaImage;`.
