### ISSUE TITLE
Can't make the files with PointSet

### ISSUE THREAD

**Issue by gravit22** [BioMedIA/MIRTK#777]
Here is what I get when I try to make it with PointSet enabled in configuration. 
`make -j 8
[  0%] Built target gifticlib
[  0%] Linking CXX shared library ../../../lib/libMIRTKCommon.so
[  1%] Built target metaio
[  1%] Built target _extract-image-volume
[  2%] Built target nifticlib
[  3%] Built target _pythonlib
[  3%] Checking if source files for target pythonlib were added or removed
[  3%] Built target _convert-mris
[  4%] Built target _average-measure
[  4%] Built target _help-rst
[  5%] Built target _average-overlap
[  5%] Built target _evaluate-atlas
[  5%] Built target _construct-atlas
[  5%] Built target _extract-image-slice
[  5%] Built target __pythonlib
[  7%] Built target convert-mris
[  7%] Built target _mirtk
[  8%] Built target average-measure
[  8%] Built target help-rst
[  9%] Built target extract-image-volume
[ 10%] Built target evaluate-atlas
[ 10%] Built target average-overlap
[ 10%] Built target construct-atlas
[ 10%] Built target extract-image-slice
[ 10%] Built target mirtk
[ 12%] Built target pythonlib
[ 12%] Built target lib
/usr/bin/ld: /usr/local/lib/libvtkCommonCore-8.2.a(vtkBitArray.cxx.o): warning: relocation against `_ZN11vtkBitArray10InitializeEv' in read-only section `.text._ZN11vtkBitArray16WriteVoidPointerExx[_ZN11vtkBitArray16WriteVoidPointerExx]'
/usr/bin/ld: /usr/local/lib/libvtkCommonCore-8.2.a(vtkCharArray.cxx.o): relocation R_X86_64_PC32 against symbol `_ZTV12vtkCharArray' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Modules/Common/src/CMakeFiles/LibCommon.dir/build.make:324: lib/libMIRTKCommon.so.0.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:1504: Modules/Common/src/CMakeFiles/LibCommon.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
`

**Comment by schuhschuh** [comment]
I assume you get this error because you are linking to a static build of VTK, which was created without the `-fPIC` compiler flag. You would either have to rebuild VTK with this flag (by adding it to CMAKE_CXX_FLAGS when building VTK), or use shared VTK libraries (recommended).
